insert into dt_team_constraints values (1, 'No constraint',        0, null, 1, 0, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1);
insert into dt_team_constraints values (2, 'Classical',            0, null, 1, 0, 1, 8, 8, 6, 6, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1);
insert into dt_team_constraints values (3, 'Limited',              0, null, 1, 0, 1, 8, 8, 6, 6, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1, -1, 1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1);
insert into dt_team_constraints values (4, 'Classical - Official', 0, null, 1, 0, 1, 8, 8, 6, 6, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1);
insert into dt_team_constraints values (5, 'Limited - Official',   0, null, 1, 0, 1, 8, 8, 6, 6, 2, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1, -1, 1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 1);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 2);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 3);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 4);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 5);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 6);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 7);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 8);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 9);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (4, 10);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 1);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 2);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 3);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 4);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 5);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 6);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 7);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 8);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 9);
insert into dt_team_constraints_extensions (dtteamconstraint_id, dtextension_id) values (5, 10);
